### ISSUE TITLE
Visible Member List Categories

### ISSUE THREAD

**Issue by Jadecca** [ddavaham/pinger#3]
Please add categories to memberslist so Admins, SkyMarshalls, and FC's are clearly distinguished.
Please also include categories for FCs, as Torrin has divided them:
tier 1, 2, 3, Cap FC, and Logi FC

Ah, please make these assignable by the SkyMarshall

**Comment by ddavaham** [comment]
Resolves with 583af91e846d90476fc8b4d2d48fe05cb4545b8d

Below each members name on the members list will be a small pill label with the permissions they have assigned to them. Click on any of these pills will filter the list down to members who have that pemrissions
