### ISSUE TITLE
Expand Ping Options

### ISSUE THREAD

**Issue by Jadecca** [ddavaham/pinger#7]
Please add a new set of Discord Ping options, with the addition of a secondary "Prehurf" label (additional to TBA/CTA/StratOp ect) which applies if the ping is submitted :

Unchecked ping to discord box = instances where a fleet is tentative, i.e. not yet relatively set in stone. Does not force the selection of prehurfs.
"Ping To Discord Now" = If fleet is more than an hr out, it receives the additional Prehurf label with a "Time Till" stamp. If the fleet is more than an hr out, forces the selection of one or more of the prehurf options
"Ping Later" = Doesn't ping discord, forces the selection of one or more prehurf options

Prehurf options. These options send out a ping at a certain time interval prior to the fleet's scheduled time:

48hrs
24hrs
12hrs
6hrs
3hrs
2hrs
1hr
30mins
15mins

In addition to any of the prehurf timers selected, a ping goes out at the time of formup as well.
This might look like a lot of pings, as a guard against an FC setting this up so each and every prehurf ping goes out please limite prehurf selection to no more than 3 for all FCs except the SkyMarshall, and if not too much hassle admins as well.

**Comment by ddavaham** [comment]
Prehurfs are reminders. Not a type of Fleet. The word Prehurf will follow the mention (if a mention is set on the fleet) when a ping goes out unless it is the ping signalling the start of the fleet.
