### ISSUE TITLE
Pinger gives option to select Discord Server

### ISSUE THREAD

**Issue by Wirespeed91** [ddavaham/pinger#9]
When "Ping Discord on Submission of Fleet" is selected, Pinger gives us the option to select a Discord Server out of the current ones that have the Webhook. Current Options are DHS and Pinger. For long-term use, might be best to limit this?

**Comment by ddavaham** [comment]
Those were channels, not servers, and i believe that Cain cleared this up already as I am seeing different options available now, however I should probably change the wording to say Webhook instead of Server
